AllCops:
  NewCops: enable
  SuggestExtensions:
    rubocop-rake: false
Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space
Lint/RedundantCopDisableDirective:
  Enabled: false
